[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "chisa"
version = "0.1.1"
description = "A logic-driven dimensional algebra and strict physics modeling framework."
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
    {name = "Zahraan Dzakii Tsaqiif", email = "zahraandzakiits@gmail.com"}
]
keywords = [
    "physics", "unit conversion", "dimensional analysis", 
    "engineering", "science", "metrology", "astrophysics", "numpy"
]

dependencies = [
    "numpy>=1.26.0"
]
classifiers = [
    # Development Status
    "Development Status :: 4 - Beta",
    
    # Intended Audiences
    "Intended Audience :: Developers",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    
    # Topics
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Physics",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
    
    # License & Environment
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    
    # Supported Python Versions
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13"
]

[tool.setuptools.packages.find]
where = ["src"]